version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-browsers
    environment:
      PYTHONPATH: ~/repo

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt --quiet

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: lint
          command: |
            . venv/bin/activate
            pylint pytest_dash tests test_apps
            flake8

      - run:
          name: format diff with yapf
          command: |
            . venv/bin/activate
            yapf pytest_dash tests test_apps -rd

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -e .
            pytest --cov=pytest_dash
            cp .coverage test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
